### ISSUE TITLE
Where do I add licence key 

### ISSUE THREAD

**Issue by mayur-sarang** [googlecodelabs/play-billing-codelab#1]
I didn't found any Licence key added, which is Base64-encoded, Where to add?

**Comment by gorgon** [comment]
You don't need to add any license key. Did you find some guidelines that require it?

**Comment by mayur-sarang** [comment]
![screenshot from 2017-07-17 12 20 02](https://user-images.githubusercontent.com/20282328/28257866-6d74d982-6aeb-11e7-84e9-fd62acffd018.png)

This is written in Google play console(Development tools > service &api)

**Comment by gorgon** [comment]
Codelab sample code already contains this part (it has both signature file and necessary changes inside build.gradle file inside work dir). You can check it out and use this technics for your own app. However it's not the main part of this codelab and you don't need to worry about this to complete it.

**Comment by maxim-yudin** [comment]
Thanks

**Comment by gorgon** [comment]
We tried to keep the Codelab as short as possible.
For the complete sample example, please see, how we are using Base64 key [in TrivialDrive v2](https://github.com/googlesamples/android-play-billing/blob/master/TrivialDrive_v2/shared-module/src/main/java/com/example/billingmodule/billing/BillingManager.java#L384).
But please, keep in mind, that this couldn't be the main security part in your integration with Google Play billing. We do encourage developers to think about their ways of providing a security level specific to their needs and use [our backend API](https://developers.google.com/android-publisher/api-ref/purchases/products/get) for purchase verification.
