### ISSUE TITLE
Once it is rotated, the AquireFragment only displays the wait screen.

### ISSUE THREAD

**Issue by dmmearns** [googlecodelabs/play-billing-codelab#4]
If the AcquireFragment is showing and I rotate the screen, GamePlayActivity onCreate is called again, causing new BillingManager creation, causing startServiceConnectionIfNeeded(null) to be called. 

While that connection is being established, startServiceConnectionIfNeeded also gets called via AcquireFragment.handleManagerAndUiReady(), causing onBillingSetupFinished() to run with error code 5 (developer error) because "Client is already in the process of connecting to billing service." (warning from BillingClientImpl.startConnection()). 

So setWaitScreen(false) doesn't get called from handleManagerAndUiReady() and the user would have to press back and then press purchase again to continue with the purchase flow.

@gorgon

**Comment by gorgon** [comment]
Are you talking about [TrivialDrive_v2](https://github.com/googlesamples/android-play-billing/tree/master/TrivialDrive_v2)?
There, once you rotate the screen, your activity (and so the BillingClient) should be destroyed and a new BillingClient instance should be created. So there should be no problem with the client being already in the process of connection to billing service.

**Comment by dmmearns** [comment]
Thanks @gorgon for your response. No, not TrivialDrive_v2, I'm talking about this codelab.

Yes, BillingClient is being destroyed and re-created. However, when you rotate the screen, there is much less time elapsed between the BillingClient being created and handleManagerAndUiReady() being called in AquireFragment. There is much less time elapsed because the user does not need to press the purchase button before handleManagerAndUiReady() is called.

**Comment by gorgon** [comment]
Codelab is implemented to be as short as possible, so it doesn't handle the rotation properly.
Please see [TrivialDrive_v2](https://github.com/googlesamples/android-play-billing/tree/master/TrivialDrive_v2) for proper implementation.
